version: '3'
  
services:
  reverseproxy:
    container_name: reverseproxy
    image: 774964239202.dkr.ecr.us-east-1.amazonaws.com/wrnr-nginx:v2
    ports:
      - 80:80
      - 443:443
    restart: always

  wrnr:
    container_name: wrnr
    depends_on:
      - nats
    image: 774964239202.dkr.ecr.us-east-1.amazonaws.com/wrnr-wrnr:v13
    # needs an IAM user with AmazonS3FullAccess permission
    environment:
      - aws_access_key_id=<access_key_with_S3Admin_permission>
      - aws_secret_access_key=<secret_for_key_with_S3Admin_permission>
      # - LOG_LEVEL=debug
      - WRNR_STORAGE_ROOT=/opt/wrnr/data      
      # if not provided it will get region of docker container and create a root
      # bucket wrnr-io-<region>
      # - WRNR_S3_REGION=
      # - WRNR_S3_ROOT_BUCKET=
    # expose:
    #   - 8161
    volumes:
      - <storage_space_created_on_host>:/opt/wrnr/data
    restart: always

  nats:
    container_name: nats
    image: 774964239202.dkr.ecr.us-east-1.amazonaws.com/wrnr-nats:v3
    # expose:
    #   - 4222
    #   - 8222
    restart: always
    volumes:
      - <storage_space_created_on_host>:/opt/wrnr
